Update@20210125

diff --git a/admin/syslog-ng/files/syslog-ng.init b/admin/syslog-ng/files/syslog-ng.init
--- a/admin/syslog-ng/files/syslog-ng.init
+++ b/admin/syslog-ng/files/syslog-ng.init
@@ -1,17 +1,31 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2006-2019 OpenWrt.org
+# Copyright (C) 2006-2016 OpenWrt.org
 
-START=50
+START=20
+PROG=/usr/sbin/syslog-ng
+PROG2=/usr/sbin/syslog-ng-ctl
 
-USE_PROCD=1
+SERVICE_USE_PID=1
+SERVICE_PID_FILE=/var/run/syslog-ng.pid
 
-start_service() {
-	[ -f /etc/syslog-ng.conf ] || return 1
-	procd_open_instance
-	procd_set_param command /usr/sbin/syslog-ng --foreground
-	procd_close_instance
+config_file=/etc/syslog-ng.conf
+
+start() {
+	[ -f $config_file ] || return 1
+
+	if ! $PROG -s 2>/dev/null ; then
+		echo "Couldn't parse $(basename $config_file)" >&2
+		exit 1
+	fi
+
+	service_start $PROG --process-mode background \
+		-p $SERVICE_PID_FILE
 }
 
-reload_service() {
-	/usr/sbin/syslog-ng-ctl reload
+stop() {
+	service_stop $PROG
+}
+
+reload() {
+	$PROG2 reload
 }
diff --git a/net/vnstat/files/vnstat.init b/net/vnstat/files/vnstat.init
--- a/net/vnstat/files/vnstat.init
+++ b/net/vnstat/files/vnstat.init
@@ -3,18 +3,22 @@
 
 START=99
 
-USE_PROCD=1
-
 vnstat_option() {
 	sed -ne "s/^[[:space:]]*$1[[:space:]]*['\"]\([^'\"]*\)['\"].*/\1/p" \
 		/etc/vnstat.conf
 }
 
-start_service() {
+start() {
 	local lib="$(vnstat_option DatabaseDir)"
+	local pid="$(vnstat_option PidFile)"
 
 	[ -n "$lib" ] || {
 		echo "Error: No DatabaseDir set in vnstat.conf" >&2
+		exit 1
+	}
+
+	[ -n "$pid" ] || {
+		echo "Error: No PidFile set in vnstat.conf" >&2
 		exit 1
 	}
 
@@ -68,19 +72,18 @@ start_service() {
 	config_load vnstat
 	config_foreach init_ifaces vnstat
 
-	procd_open_instance
-	procd_set_param stdout 1
-	procd_set_param stderr 1
-	procd_set_param command /usr/sbin/vnstatd --nodaemon
-	procd_set_param file /etc/vnstat.conf
-	procd_set_param respawn
-	procd_close_instance
+	SERVICE_PID_FILE="${pid}"
+	service_start /usr/sbin/vnstatd -d
 }
 
-reload_service() {
-	procd_send_signal vnstat
-}
+stop() {
+	local pid="$(vnstat_option PidFile)"
 
-service_triggers() {
-	procd_add_reload_trigger vnstat
+	[ -n "$pid" ] || {
+		echo "Error: No PidFile set in vnstat.conf" >&2
+		exit 1
+	}
+
+	SERVICE_PID_FILE="${pid}"
+	service_stop /usr/sbin/vnstatd
 }
